# wandb
wandb_project: lbm-removal-toy
timestep_sampling: custom_timesteps
unet_input_channels: 10
vae_num_channels: 4
selected_timesteps: [0, 250, 500, 750]
prob: [0.25, 0.25, 0.25, 0.25]
pixel_loss_type: lpips # l1 l2
pixel_loss_weight: 10.0
latent_loss_type: l2 # l1 l2
latent_loss_weight: 1.0
bridge_noise_sigma: 0.05
conditioning_images_keys: ["image"]
conditioning_masks_keys: ["edge", "mask"]
use_bucketing: true

# SHARDS_PATH_OR_URLS
# Using the toy set created by the user
train_shards:
  - "pipe:cat /home/ubuntu/Documents/LBM/data/toy_data_lbm/shard-*.tar"

validation_shards:
  - "pipe:cat /home/ubuntu/Documents/LBM/data/toy_data_lbm/shard-000000.tar"

batch_size: 1
learning_rate: 3e-5
optimizer: AdamW
num_steps: [1, 4]
log_interval: 1
resume_from_checkpoint: false
max_epochs: 1
max_steps: 10
save_interval: 100
save_ckpt_path: ./checkpoints_toy
source_key: masked_image
target_key: target
mask_key: mask
